import nodemailer, { Transporter } from 'nodemailer';
import { NormalizedTestResult, QaSummary } from '../types';
import { escapeHtml } from '../reporting/report';

export interface MailConfig { host: string; port: number; secure: boolean; username: string; password: string; from: string; testerEmail: string; projectManagerEmail: string; developerEmail?: string }
export interface MailTemplate { subject: string; html: string }
function emailLink(url: string): string { return url && url !== 'unavailable' ? `<a href="${escapeHtml(url)}">${escapeHtml(url)}</a>` : 'unavailable'; }
function links(summary: QaSummary, test?: NormalizedTestResult): string { return `<p>Run: ${emailLink(summary.runUrl)}<br>Report: ${emailLink(summary.reportUrl)}<br>Summary: ${emailLink(summary.summaryUrl)}${test?.jiraIssue ? `<br>Jira: ${test.jiraUrl ? `<a href="${escapeHtml(test.jiraUrl)}">${escapeHtml(test.jiraIssue)}</a>` : escapeHtml(test.jiraIssue)}` : ''}</p>`; }
function runDetails(summary: QaSummary): string { return `<p>Project: ${escapeHtml(summary.project)}<br>Environment: ${escapeHtml(summary.environment)}<br>Branch: ${escapeHtml(summary.branch)}<br>Commit: ${escapeHtml(summary.commit)}<br>Started: ${escapeHtml(summary.startedAt)}<br>Ended: ${escapeHtml(summary.endedAt)}<br>Duration: ${summary.durationMs} ms<br>Total: ${summary.totals.total}; Passed: ${summary.totals.passed}; Failed: ${summary.totals.failed}; Skipped: ${summary.totals.skipped}; Flaky: ${summary.totals.flaky}; Pass: ${summary.passPercentage}%; Fail: ${summary.failPercentage}%</p>`; }
function failureDetails(test: NormalizedTestResult): string { return `<p>Failed test: ${escapeHtml(test.title)}<br>Test ID: ${escapeHtml(test.id)}<br>Module: ${escapeHtml(test.module)}<br>Error: ${escapeHtml(test.error)}<br>Jira issue: ${escapeHtml(test.jiraIssue || 'Not created')}</p>`; }
export function renderExecutionEmail(summary: QaSummary): MailTemplate { const failures = summary.tests.filter((test) => test.status === 'failed').map(failureDetails).join(''); return { subject: `[Automation] OfficeKit UAT - Test Execution ${summary.overallResult}`, html: `<h1>Test Execution ${summary.overallResult}</h1>${runDetails(summary)}${failures}${links(summary)}` }; }
export function renderDefectEmail(summary: QaSummary, test: NormalizedTestResult): MailTemplate { return { subject: `[Automation] New Defect Created - ${test.jiraIssue}`, html: `<h1>New Defect Created</h1>${runDetails(summary)}<p>Issue: ${escapeHtml(test.jiraIssue)}<br>Test ID: ${escapeHtml(test.id)}<br>Test: ${escapeHtml(test.title)}<br>Module: ${escapeHtml(test.module)}<br>Failure: ${escapeHtml(test.error)}</p>${links(summary, test)}` }; }
export function renderVerificationEmail(summary: QaSummary, test: NormalizedTestResult): MailTemplate { const outcome = test.verificationStatus === 'passed' ? 'PASSED' : 'FAILED'; return { subject: `[Automation] Bug Verification ${outcome} - ${test.jiraIssue}`, html: `<h1>Bug Verification ${outcome}</h1><p>Jira: ${escapeHtml(test.jiraIssue)}<br>Test ID: ${escapeHtml(test.id)}<br>Test: ${escapeHtml(test.title)}<br>Module: ${escapeHtml(test.module)}<br>Environment: ${escapeHtml(summary.environment)}<br>Commit: ${escapeHtml(summary.commit)}<br>Verification result: ${outcome}<br>Failure: ${escapeHtml(test.error || 'none')}<br>Screenshot: ${escapeHtml(test.screenshot || 'unavailable')}<br>Trace: ${escapeHtml(test.trace || 'unavailable')}</p>${links(summary, test)}` }; }
export function recipients(config: MailConfig, assigneeEmail?: string): string[] { return [...new Set([config.testerEmail, config.projectManagerEmail, assigneeEmail || config.developerEmail].filter((item): item is string => Boolean(item)))]; }
export function createTransport(config: MailConfig): Transporter { return nodemailer.createTransport({ host: config.host, port: config.port, secure: config.secure, auth: { user: config.username, pass: config.password } }); }
export async function sendMail(template: MailTemplate, config: MailConfig, assigneeEmail?: string, transporter = createTransport(config)): Promise<void> { await transporter.sendMail({ from: config.from, to: recipients(config, assigneeEmail).join(','), ...template }); }
